### ISSUE TITLE
Modifier keys

### ISSUE THREAD

**Issue by WilsontheWolf** [Alex4386/decky-terminal#7]
This project is pretty neat. However, when I'm using the deck without a keyboard, i can't seem to do any kind of modifier keys. This means I can't do things like `ctrl + c`. I'm not sure if it would even be possible to modify the on screen keyboard to add modifier keys, but it might be nice to have a ctrl + c button beside the keyboard button. Thanks

**Comment by Alex4386** [comment]
Sorry for the late reply. Current keyboard implementation utilizes `SteamClient`'s native on-screen-keyboard. Currently decky-plugin doesn't support directly accessing on-screen keyboard at the moment. So adding modifier keys on on screen keyboard might not be trivial at the moment.  
  
For the alternative implementation, it seems adding buttons for mostly-used unix signals are a good idea: e.g. <kbd>Ctrl</kbd>+<kbd>C</kbd> or <kbd>Ctrl</kbd>+<kbd>D</kbd>. Since the app has free space allocated for the virtual keyboard if the "handheld-mode" is activated. will look into it.

**Comment by Alex4386** [comment]
Allocated for v0.4.0 Release

**Comment by Alex4386** [comment]
Function rows are now here!  
![image](https://github.com/Alex4386/decky-terminal/assets/27724108/93b5d707-51f7-49c6-92b1-54a163a20333)
![image](https://github.com/Alex4386/decky-terminal/assets/27724108/2717a63b-6b61-46f4-826f-f89d1059fe87)

**Comment by Alex4386** [comment]
You can now toggle the function row in Settings. (`v0.4.0`)  
![image](https://github.com/Alex4386/decky-terminal/assets/27724108/7ae0e0fb-2a79-4aef-ae6c-ef7f2ec861b1)

**Comment by Alex4386** [comment]
Will close this issue when `v0.4.0` gets merged into https://github.com/SteamDeckHomebrew/decky-plugin-database.  
**Thanks for the feature request :D**

**Comment by Alex4386** [comment]
Currently tracking release at https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/580.

**Comment by Alex4386** [comment]
`v0.4.1` Merged to upstream. closing issue.
